synhsi_hand:
  _target_: models.synhsi.Unet
  dim_model: 512
  num_heads: 16
  num_layers: 8
  dropout_p: 0.1
  nb_voxels: ${dataset.nb_voxels}
  free_p: 0
  ac_type: last_add_first_token
  dim_input: ${times:${dataset.nb_joints},3}
  dim_output: ${times:${dataset.nb_joints},3}
  nb_actions: ${dataset.nb_actions}
  no_scene: ${guidance.right_hand.no_scene}
  no_action: ${guidance.right_hand.no_action}
  ckpt: ${ckpt_dir}/TRUMANS_mask_ind[23]_timesteps[100]_fixed_frame[2]_ac_type[last_add_first_token]_no_scene[False]_no_action[True]_batch_size[256]_epoch360.pth
#  ckpt: ${ckpt_dir}/train_synhsi_prox_hand_epoch280.pth
#  ckpt: ${ckpt_dir}/train_synhsi_grab_right_hand_epoch000.pth